with guide_updates as (
  select value
  from jsonb_array_elements($guide_updates$[
    {"slug":"cherry-studio","source_url":"https://github.com/CherryHQ/cherry-studio#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Choose the Windows installer from the official releases page","download_url":"https://github.com/CherryHQ/cherry-studio/releases/latest"},"macos":{"support":"supported","install_route":"Choose the macOS installer from the official releases page","download_url":"https://github.com/CherryHQ/cherry-studio/releases/latest"},"linux":{"support":"supported","install_route":"Choose the Linux package from the official releases page","download_url":"https://github.com/CherryHQ/cherry-studio/releases/latest"}}},
    {"slug":"command-code","source_url":"https://github.com/CommandCodeAI/command-code#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Global npm package","install_commands":["npm install -g command-code"],"first_run_commands":["cmd"]},"macos":{"support":"supported","install_route":"Global npm package","install_commands":["npm install -g command-code"],"first_run_commands":["cmd"]},"linux":{"support":"supported","install_route":"Global npm package","install_commands":["npm install -g command-code"],"first_run_commands":["cmd"]}}},
    {"slug":"codebuff","source_url":"https://github.com/CodebuffAI/freebuff#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Freebuff CLI (the upstream project formerly called Codebuff)","install_commands":["npm install -g freebuff"]},"macos":{"support":"supported","install_route":"Freebuff CLI (the upstream project formerly called Codebuff)","install_commands":["npm install -g freebuff"]},"linux":{"support":"supported","install_route":"Freebuff CLI (the upstream project formerly called Codebuff)","install_commands":["npm install -g freebuff"]}}},
    {"slug":"cline","source_url":"https://github.com/cline/cline#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Cline CLI; the desktop app is also available for Windows","download_url":"https://cline.bot/desktop","install_commands":["npm install -g cline"]},"macos":{"support":"supported","install_route":"Cline CLI; the desktop app is also available for macOS","download_url":"https://cline.bot/desktop","install_commands":["npm install -g cline"]},"linux":{"support":"supported","install_route":"Cline CLI","install_commands":["npm install -g cline"]}}},
    {"slug":"insights-lm-public","source_url":"https://github.com/theaiautomators/insights-lm-public#readme","checked_at":"2026-10-07","notes":"These commands run the Vite frontend only. The complete application also requires a Supabase project, deployed edge functions, configured n8n workflows and secrets; upstream's quick-start recommends Bolt.new for full-stack setup.","platforms":{"windows":{"support":"supported","install_route":"Vite frontend source; configure the Supabase environment before use","prerequisites":["Node.js and npm","Supabase project and n8n instance"],"install_commands":["git clone https://github.com/theaiautomators/insights-lm-public.git","cd insights-lm-public","npm install"],"first_run_commands":["npm run dev"],"first_run_steps":["Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY for the frontend.","Follow the upstream README to deploy Supabase migrations and edge functions, configure n8n workflows, and set required secrets."]},"macos":{"support":"supported","install_route":"Vite frontend source; configure the Supabase environment before use","prerequisites":["Node.js and npm","Supabase project and n8n instance"],"install_commands":["git clone https://github.com/theaiautomators/insights-lm-public.git","cd insights-lm-public","npm install"],"first_run_commands":["npm run dev"],"first_run_steps":["Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY for the frontend.","Follow the upstream README to deploy Supabase migrations and edge functions, configure n8n workflows, and set required secrets."]},"linux":{"support":"supported","install_route":"Vite frontend source; configure the Supabase environment before use","prerequisites":["Node.js and npm","Supabase project and n8n instance"],"install_commands":["git clone https://github.com/theaiautomators/insights-lm-public.git","cd insights-lm-public","npm install"],"first_run_commands":["npm run dev"],"first_run_steps":["Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY for the frontend.","Follow the upstream README to deploy Supabase migrations and edge functions, configure n8n workflows, and set required secrets."]}}},
    {"slug":"kilocode","source_url":"https://github.com/Kilo-Org/kilocode#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Install the Kilo Code CLI with npm","install_commands":["npm install -g @kilocode/cli"]}}},
    {"slug":"librechat","source_url":"https://www.librechat.ai/docs/quick_start/local_setup","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Docker Compose; Docker Desktop recommended","prerequisites":["Git","Docker Desktop or Docker Engine with Compose"],"install_commands":["git clone https://github.com/LibreChat-AI/LibreChat.git","cd LibreChat","Copy-Item .env.example .env","docker compose up -d"],"first_run_steps":["Configure required values in .env before starting the services.","Open http://localhost:3080, create an account, and add a provider API key."]},"macos":{"support":"supported","install_route":"Docker Compose; Docker Desktop recommended","prerequisites":["Git","Docker Desktop or Docker Engine with Compose"],"install_commands":["git clone https://github.com/LibreChat-AI/LibreChat.git","cd LibreChat","cp .env.example .env","docker compose up -d"],"first_run_steps":["Configure required values in .env before starting the services.","Open http://localhost:3080, create an account, and add a provider API key."]},"linux":{"support":"supported","install_route":"Docker Compose; Docker Engine with Compose recommended","prerequisites":["Git","Docker Engine with Compose"],"install_commands":["git clone https://github.com/LibreChat-AI/LibreChat.git","cd LibreChat","cp .env.example .env","docker compose up -d"],"first_run_steps":["Configure required values in .env before starting the services.","Open http://localhost:3080, create an account, and add a provider API key."]}}},
    {"slug":"browseros","source_url":"https://github.com/browseros-ai/BrowserOS#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Windows x64 installer","download_url":"https://cdn.browseros.com/download/BrowserOS_neo_installer.exe"},"linux":{"support":"supported","install_route":"Linux x64 AppImage","download_url":"https://cdn.browseros.com/download/BrowserOS_neo.AppImage"}}},
    {"slug":"surfsense","source_url":"https://github.com/MODSetter/SurfSense#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Windows x64 installer","download_url":"https://github.com/MODSetter/SurfSense/releases/latest/download/SurfSense-Setup.exe"},"macos":{"support":"supported","install_route":"macOS Apple Silicon disk image","download_url":"https://github.com/MODSetter/SurfSense/releases/latest/download/SurfSense-arm64.dmg"},"linux":{"support":"supported","install_route":"Linux x64 AppImage or Debian package","download_url":"https://github.com/MODSetter/SurfSense/releases/latest/download/SurfSense.AppImage"}}},
    {"slug":"node-banana","source_url":"https://github.com/shrimbly/node-banana/blob/master/README.md","checked_at":"2026-10-07","platforms":{"macos":{"support":"supported","install_route":"Apple Silicon; macOS 13 or later","download_url":"https://nodebanana.app/download/mac"}}},
    {"slug":"swe-agent","source_url":"https://github.com/SWE-agent/SWE-agent/blob/main/docs/installation/source.md","checked_at":"2026-10-07","notes":"The SWE-agent README recommends mini-SWE-agent for new users; this entry is for users who specifically need this legacy project.","platforms":{"windows":{"support":"supported","install_route":"Install from source; upstream recommends mini-SWE-agent for new users","prerequisites":["Python","Git","A model provider API key; Docker is recommended for the default execution backend"],"install_commands":["git clone https://github.com/SWE-agent/SWE-agent.git","cd SWE-agent","python -m pip install --upgrade pip","python -m pip install --editable ."],"first_run_commands":["sweagent --help"],"first_run_steps":["Configure a language model as described in the upstream installation guide.","Install and start Docker for the default local execution backend."]},"macos":{"support":"supported","install_route":"Install from source; upstream recommends mini-SWE-agent for new users","prerequisites":["Python","Git","A model provider API key; Docker is recommended for the default execution backend"],"install_commands":["git clone https://github.com/SWE-agent/SWE-agent.git","cd SWE-agent","python -m pip install --upgrade pip","python -m pip install --editable ."],"first_run_commands":["sweagent --help"],"first_run_steps":["Configure a language model as described in the upstream installation guide.","Install and start Docker for the default local execution backend."]},"linux":{"support":"supported","install_route":"Install from source; upstream recommends mini-SWE-agent for new users","prerequisites":["Python","Git","A model provider API key; Docker is recommended for the default execution backend"],"install_commands":["git clone https://github.com/SWE-agent/SWE-agent.git","cd SWE-agent","python -m pip install --upgrade pip","python -m pip install --editable ."],"first_run_commands":["sweagent --help"],"first_run_steps":["Configure a language model as described in the upstream installation guide.","Install and start Docker for the default local execution backend."]}}},
    {"slug":"smartsub","source_url":"https://github.com/buxuku/SmartSub#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Windows x64 installer","download_url":"https://github.com/buxuku/SmartSub/releases/latest"},"linux":{"support":"supported","install_route":"Linux x64 AppImage or Debian package","download_url":"https://github.com/buxuku/SmartSub/releases/latest"}}},
    {"slug":"skales","source_url":"https://github.com/skalesapp/skales#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Windows installer","download_url":"https://skales.app/download/latest-windows"},"macos":{"support":"supported","install_route":"Choose the Apple Silicon or Intel macOS installer from the official download page","download_url":"https://github.com/skalesapp/skales/releases/latest"},"linux":{"support":"supported","install_route":"Linux installer","download_url":"https://skales.app/download/latest-linux"}}},
    {"slug":"opencreator","source_url":"https://github.com/krillinai/OpenCreator#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Windows x64 desktop installer","download_url":"https://github.com/krillinai/OpenCreator/releases/latest"},"macos":{"support":"supported","install_route":"Choose the Apple Silicon or Intel macOS desktop installer","download_url":"https://github.com/krillinai/OpenCreator/releases/latest"}}},
    {"slug":"invokeai","source_url":"https://github.com/invoke-ai/InvokeAI#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Download the Invoke Launcher for Windows","download_url":"https://github.com/invoke-ai/launcher/releases/latest"},"macos":{"support":"supported","install_route":"Download the Invoke Launcher for macOS","download_url":"https://github.com/invoke-ai/launcher/releases/latest"},"linux":{"support":"supported","install_route":"Download the Invoke Launcher for Linux","download_url":"https://github.com/invoke-ai/launcher/releases/latest"}}},
    {"slug":"deep-research","source_url":"https://github.com/dzhng/deep-research#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Node.js project setup","install_commands":["git clone https://github.com/dzhng/deep-research.git","cd deep-research","npm install"],"first_run_commands":["npm start"]},"macos":{"support":"supported","install_route":"Node.js project setup","install_commands":["git clone https://github.com/dzhng/deep-research.git","cd deep-research","npm install"],"first_run_commands":["npm start"]},"linux":{"support":"supported","install_route":"Node.js project setup","install_commands":["git clone https://github.com/dzhng/deep-research.git","cd deep-research","npm install"],"first_run_commands":["npm start"]}}},
    {"slug":"deep-research-web-ui","source_url":"https://github.com/AnotiaWang/deep-research-web-ui#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Docker; configure API keys in the browser in Client Mode","install_commands":["docker run -p 3000:3000 --name deep-research-web -d anotia/deep-research-web:latest"]},"macos":{"support":"supported","install_route":"Docker; configure API keys in the browser in Client Mode","install_commands":["docker run -p 3000:3000 --name deep-research-web -d anotia/deep-research-web:latest"]},"linux":{"support":"supported","install_route":"Docker; configure API keys in the browser in Client Mode","install_commands":["docker run -p 3000:3000 --name deep-research-web -d anotia/deep-research-web:latest"]}}},
    {"slug":"gpt-researcher","source_url":"https://github.com/assafelovic/gpt-researcher#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Python package; Python 3.11 or later","install_commands":["pip install gpt-researcher"]},"macos":{"support":"supported","install_route":"Python package; Python 3.11 or later","install_commands":["pip install gpt-researcher"]},"linux":{"support":"supported","install_route":"Python package; Python 3.11 or later","install_commands":["pip install gpt-researcher"]}}},
    {"slug":"gptme","source_url":"https://github.com/gptme/gptme#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Recommended: pipx; requires Python 3.10 or later","install_commands":["pipx install gptme"]},"macos":{"support":"supported","install_route":"Recommended: pipx; requires Python 3.10 or later","install_commands":["pipx install gptme"]},"linux":{"support":"supported","install_route":"Recommended: pipx; requires Python 3.10 or later","install_commands":["pipx install gptme"]}}},
    {"slug":"mini-swe-agent","source_url":"https://github.com/SWE-agent/mini-swe-agent#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Python package","install_commands":["pip install mini-swe-agent"],"first_run_commands":["mini"]},"macos":{"support":"supported","install_route":"Python package","install_commands":["pip install mini-swe-agent"],"first_run_commands":["mini"]},"linux":{"support":"supported","install_route":"Python package","install_commands":["pip install mini-swe-agent"],"first_run_commands":["mini"]}}},
    {"slug":"onyx","source_url":"https://github.com/onyx-dot-app/onyx#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Run the official shell installer in WSL2","install_commands":["curl -fsSL https://onyx.app/install_onyx.sh | bash"]},"macos":{"support":"supported","install_route":"Official shell installer","install_commands":["curl -fsSL https://onyx.app/install_onyx.sh | bash"]},"linux":{"support":"supported","install_route":"Official shell installer","install_commands":["curl -fsSL https://onyx.app/install_onyx.sh | bash"]}}},
    {"slug":"open-webui","source_url":"https://github.com/open-webui/open-webui#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Python 3.11","install_commands":["pip install open-webui"],"first_run_commands":["open-webui serve"]},"macos":{"support":"supported","install_route":"Python 3.11","install_commands":["pip install open-webui"],"first_run_commands":["open-webui serve"]},"linux":{"support":"supported","install_route":"Python 3.11","install_commands":["pip install open-webui"],"first_run_commands":["open-webui serve"]}}},
    {"slug":"openhands","source_url":"https://github.com/OpenHands/OpenHands#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Node.js 24 or later and uv required; use WSL2 for multiple Docker sandboxes","install_commands":["npm install -g @openhands/agent-canvas","agent-canvas"]},"macos":{"support":"supported","install_route":"Node.js 24 or later and uv required","install_commands":["npm install -g @openhands/agent-canvas","agent-canvas"]},"linux":{"support":"supported","install_route":"Node.js 24 or later and uv required","install_commands":["npm install -g @openhands/agent-canvas","agent-canvas"]}}},
    {"slug":"paperqa","source_url":"https://github.com/Future-House/paper-qa#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Python package","install_commands":["pip install \"paper-qa>=5\""]},"macos":{"support":"supported","install_route":"Python package","install_commands":["pip install \"paper-qa>=5\""]},"linux":{"support":"supported","install_route":"Python package","install_commands":["pip install \"paper-qa>=5\""]}}},
    {"slug":"pentest-ai","source_url":"https://github.com/0xSteph/pentest-ai#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Requires pipx and Python 3.10 to 3.14","install_commands":["pipx install ptai"]},"macos":{"support":"supported","install_route":"Requires pipx and Python 3.10 to 3.14","install_commands":["pipx install ptai"]},"linux":{"support":"supported","install_route":"Requires pipx and Python 3.10 to 3.14","install_commands":["pipx install ptai"]}}},
    {"slug":"pr-agent","source_url":"https://github.com/the-pr-agent/pr-agent#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Python package with GitHub provider support","install_commands":["pip install \"pr-agent[github]\""]},"macos":{"support":"supported","install_route":"Python package with GitHub provider support","install_commands":["pip install \"pr-agent[github]\""]},"linux":{"support":"supported","install_route":"Python package with GitHub provider support","install_commands":["pip install \"pr-agent[github]\""]}}},
    {"slug":"surf","source_url":"https://github.com/e2b-dev/surf#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Node.js project setup; E2B and OpenAI API keys required","install_commands":["git clone https://github.com/e2b-dev/surf.git","cd surf","npm install"],"first_run_commands":["npm run dev"]},"macos":{"support":"supported","install_route":"Node.js project setup; E2B and OpenAI API keys required","install_commands":["git clone https://github.com/e2b-dev/surf.git","cd surf","npm install"],"first_run_commands":["npm run dev"]},"linux":{"support":"supported","install_route":"Node.js project setup; E2B and OpenAI API keys required","install_commands":["git clone https://github.com/e2b-dev/surf.git","cd surf","npm install"],"first_run_commands":["npm run dev"]}}},
    {"slug":"vibe-workflow","source_url":"https://github.com/SamurAIGPT/Vibe-Workflow#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Docker Compose v2","install_commands":["git clone https://github.com/SamurAIGPT/Vibe-Workflow.git","cd Vibe-Workflow","docker compose up --build"]},"macos":{"support":"supported","install_route":"Docker Compose v2","install_commands":["git clone https://github.com/SamurAIGPT/Vibe-Workflow.git","cd Vibe-Workflow","docker compose up --build"]},"linux":{"support":"supported","install_route":"Docker Compose v2","install_commands":["git clone https://github.com/SamurAIGPT/Vibe-Workflow.git","cd Vibe-Workflow","docker compose up --build"]}}},
    {"slug":"lobehub","source_url":"https://github.com/lobehub/lobehub#readme","checked_at":"2026-10-07","platforms":{"windows":{"support":"supported","install_route":"Docker Compose via WSL2","install_commands":["mkdir -p lobehub-db && cd lobehub-db","bash <(curl -fsSL https://lobe.li/setup.sh)","docker compose up -d"]},"macos":{"support":"supported","install_route":"Docker Compose","install_commands":["mkdir -p lobehub-db && cd lobehub-db","bash <(curl -fsSL https://lobe.li/setup.sh)","docker compose up -d"]},"linux":{"support":"supported","install_route":"Docker Compose","install_commands":["mkdir -p lobehub-db && cd lobehub-db","bash <(curl -fsSL https://lobe.li/setup.sh)","docker compose up -d"]}}}
  ]$guide_updates$::jsonb)
),
platform_updates as (
  select
    agents.id,
    jsonb_object_agg(
      seeded_platform.key,
      case
        when seeded_platform.value ? 'install_commands'
          and (
            coalesce(existing_platform.value->'install_commands', '[]'::jsonb) = '[]'::jsonb
            or existing_platform.value->'install_commands' = 'null'::jsonb
          )
        then jsonb_set(
          seeded_platform.value || coalesce(existing_platform.value, '{}'::jsonb),
          '{install_commands}',
          seeded_platform.value->'install_commands',
          true
        )
        else seeded_platform.value || coalesce(existing_platform.value, '{}'::jsonb)
      end
    ) as platforms
  from guide_updates
  join public.agents on agents.slug = guide_updates.value->>'slug'
  cross join lateral jsonb_each(guide_updates.value->'platforms') as seeded_platform
  left join lateral (
    select agents.setup_guide->'platforms'->seeded_platform.key as value
  ) as existing_platform on true
  group by agents.id
)
update public.agents
set setup_guide =
  coalesce(agents.setup_guide, '{}'::jsonb)
  || jsonb_build_object(
    'source_url', coalesce(agents.setup_guide->'source_url', guide_updates.value->'source_url'),
    'checked_at', guide_updates.value->'checked_at',
    'platforms',
      coalesce(agents.setup_guide->'platforms', '{}'::jsonb)
      || platform_updates.platforms
  )
from guide_updates
join platform_updates on true
where agents.slug = guide_updates.value->>'slug'
  and agents.id = platform_updates.id;
